apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-cubix-cn.fullname" . }}
  labels:
    {{- include "spring-cubix-cn.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spring-cubix-cn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spring-cubix-cn.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spring-cubix-cn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and .Values.configMap.enabled (eq .Values.configMap.as "file") }} 
      volumes:
      - name: config
        configMap:
          name: {{ include "spring-cubix-cn.fullname" . }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ required "Image must be set in Values" .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if and .Values.configMap.enabled (eq .Values.configMap.as "file") }} 
          volumeMounts:
          - name: config
            mountPath: /config
          {{- end }}
          env:
          - name: JAVA_OPTS
            value: {{ .Values.javaOpts | quote }}
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
          - name: SPRING_PROFILES_ACTIVE
            value: "{{ required "Logging mode must be set in Values (loggingMode), one of: stdout, stdout-json, file, file-json" .Values.loggingMode }}"
          - name: SERVER_PORT
            value: "8080"
          - name: MANAGEMENT_SERVER_PORT
            value: "8081"
          - name: OTEL_SERVICE_NAME
            value: {{ include "spring-cubix-cn.fullname" . }}
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: {{ required "OpenTelemetry target URL is required!" .Values.openTelemetry.targetUrl }}
          - name: OTEL_METRICS_EXPORTER
            value: none            
          - name: TARGET_API_KEY
            valueFrom: 
              secretKeyRef:
                name: "cnsecret"
                key: "apikey"
          startupProbe:
            periodSeconds: 1
            failureThreshold: 30
            httpGet:
              port: management
              path: /actuator/health/liveness
          livenessProbe:
            periodSeconds: 10
            failureThreshold: 2
            httpGet:
              port: management
              path: /actuator/health/liveness
          readinessProbe:
            periodSeconds: 5
            failureThreshold: 1
            httpGet:
              port: management
              path: /actuator/health/readiness
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 8081
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
